name: ❓ Question
description: Ask a question about using Audiobook Creator TTS
title: "[Question]: "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please fill out the form below.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation and Setup
        - Document Mode Usage
        - Text Mode Usage
        - Voice Selection
        - Audio Output and Quality
        - File Format Support
        - Troubleshooting
        - Performance and Optimization
        - Other
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: I tried...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Please provide your environment details if relevant
      value: |
        - OS: [e.g. macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python Version: [e.g. 3.11.5]
        - Mode: [Document/Text/Manual Cookie]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about your question
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have read the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
